export const ON_CHANGE_DATA = "ON_CHANGE_DATA";

export const LOGIN_REQUEST = "LOGIN_REQUEST";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const SEARCH_BOOK_REQUEST = "SEARCH_BOOK_REQUEST";

export const SEARCH_BOOK_SUCCESS = "SEARCH_BOOK_SUCCESS";

export const SEARCH_BOOK_FAILURE = "SEARCH_BOOK_FAILURE";

export const LIST_BOOKS_REQUEST = "LIST_BOOKS_REQUEST";

export const LIST_BOOKS_SUCCESS = "LIST_BOOKS_SUCCESS";

export const LIST_BOOKS_FAILURE = "LIST_BOOKS_FAILURE";

export const BOOK_DETAIL_REQUEST = "BOOK_DETAIL_REQUEST";

export const BOOK_DETAIL_SUCCESS = "BOOK_DETAIL_SUCCESS";

export const BOOK_DETAIL_FAILURE = "BOOK_DETAIL_FAILURE";
